source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/chuangyi0128/SLPodsRepo.git'


target 'ThirdPartAccount', :exclusive => true do
  pod "ThirdPartAccount", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ThirdPartAccount", :path => "../"
end
